In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('pokemon.csv')

In [3]:
df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [4]:
df.describe()

#      Total          HP      Attack     Defense     Sp. Atk  \
count  800.000000  800.00000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750  435.10250   69.258750   79.001250   73.842500   72.820000   
std    208.343798  119.96304   25.534669   32.457366   31.183501   32.722294   
min      1.000000  180.00000    1.000000    5.000000    5.000000   10.000000   
25%    184.750000  330.00000   50.000000   55.000000   50.000000   49.750000   
50%    364.500000  450.00000   65.000000   75.000000   70.000000   65.000000   
75%    539.250000  515.00000   80.000000  100.000000   90.000000   95.000000   
max    721.000000  780.00000  255.000000  190.000000  230.000000  194.000000   

          Sp. Def       Speed  Generation  
count  800.000000  800.000000   800.00000  
mean    71.902500   68.277500     3.32375  
std     27.828916   29.060474     1.66129  
min     20.000000    5.000000     1.00000  
25%     50.000000   45.000000     2.00000  
50%     70.000000   65.000000     3.00000  
75%     90.000000   90.000000     5.00000  
max    230.000000  180.000000     6.00000

In [5]:
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [6]:
X = df.drop(['Type 1'], axis=1)
X = pd.get_dummies(X)
Y = df['Type 1']

In [7]:
X.head()

#  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
0  1    318  45      49       49       65       65     45           1   
1  2    405  60      62       63       80       80     60           1   
2  3    525  80      82       83      100      100     80           1   
3  3    625  80     100      123      122      120     80           1   
4  4    309  39      52       43       60       50     65           1   

   Legendary      ...       Type 2_Ghost  Type 2_Grass  Type 2_Ground  \
0      False      ...                  0             0              0   
1      False      ...                  0             0              0   
2      False      ...                  0             0              0   
3      False      ...                  0             0              0   
4      False      ...                  0             0              0   

   Type 2_Ice  Type 2_Normal  Type 2_Poison  Type 2_Psychic  Type 2_Rock  \
0           0              0              1               0            0   
1           0              0              1               0            0   
2           0              0              1               0            0   
3           0              0              1               0            0   
4           0              0              0               0            0   

   Type 2_Steel  Type 2_Water  
0             0             0  
1             0             0  
2             0             0  
3             0             0  
4             0             0  

[5 rows x 828 columns]

In [8]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()

rfc.fit(X, Y)

cross_val_score(rfc, X, Y, cv=5)

c:\users\todd\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


array([0.16071429, 0.17365269, 0.19620253, 0.21794872, 0.1192053 ])

In [9]:
rfc.score(X, Y)

0.99125

In [10]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(500, 500, 500, ))
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(500, 500, 500), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [11]:
mlp.score(X, Y)

0.48875

In [12]:
Y.value_counts()/len(Y)

Water       0.14000
Normal      0.12250
Grass       0.08750
Bug         0.08625
Psychic     0.07125
Fire        0.06500
Rock        0.05500
Electric    0.05500
Dragon      0.04000
Ground      0.04000
Ghost       0.04000
Dark        0.03875
Poison      0.03500
Fighting    0.03375
Steel       0.03375
Ice         0.03000
Fairy       0.02125
Flying      0.00500
Name: Type 1, dtype: float64

In [13]:
cross_val_score(mlp, X, Y, cv=5)

c:\users\todd\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


array([0.11309524, 0.1497006 , 0.1835443 , 0.13461538, 0.13907285])

In [14]:
mlp = MLPClassifier(hidden_layer_sizes=(1000, ))
mlp.fit(X, Y)

mlp.score(X, Y)

0.56

In [15]:
cross_val_score(mlp, X, Y, cv=5)

c:\users\todd\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


array([0.14880952, 0.19161677, 0.17721519, 0.21794872, 0.0794702 ])

In [16]:
mlp = MLPClassifier(hidden_layer_sizes=(1000, 1000, ))
mlp.fit(X, Y)

mlp.score(X, Y)

0.60625